name: Build and Deploy JAR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PASS: ${{ secrets.SSH_PASS }}

    steps:
      - name: check variables
        if: ${{env.SSH_PASS}} != '' && ${{env.SSH_USER}} != '' && ${{env.SSH_HOST}} != ''
        run: |
          echo "Variables de entorno no vacias"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with: 
          java-version: '8'
          distribution: 'temurin'

      - name: Build and package
        run: |
          mvn clean package

      - name: Subir archivo por SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_HOST }}
          port: 2022
          local_path: 'target/WarningPoints-1.0.jar'
          remote_path: '/plugins/WarningPoints-TEST.jar'
          password: ${{ secrets.SSH_PASS }}