name: Build and Deploy JAR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with: 
          java-version: '8'
          distribution: 'temurin'

      - name: Build and package
        run: |
          mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WarningPoints
          path: WarningPoints-1.0.jar
      
      - name: Send .jar to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: sftp
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          local-dir: target/WarningPoints-1.0.jar
          remote-dir: /plugins/WarningPoints-TEST.jar