name: Build and Deploy JAR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with: 
          java-version: '8'
          distribution: 'temurin'

      - name: Build and package
        run: |
          mvn clean package

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: WarningPoints
      #     path: WarningPoints-1.0.jar
      
      # - name: Deploy file updateing secrest
      #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #   with:
      #       username: ${{ secrets.SSH_USER }}
      #       server: ${{ secrets.SSH_HOST }}
      #       port: 22
      #       local_path: 'target/WarningPoints-1.0.jar'
      #       remote_path: '/plugins/WarningPoints-TEST.jar'
      #       sftp_only: false
      #       password: ${{ secrets.SSH_PASS }}

      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          password: {{ secrets.SSH_PASS }}
          localPath: 'target/WarningPoints-1.0.jar'
          remotePath: '/plugins/WarningPoints-TEST.jar'