name: Build and Deploy JAR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # SSH_USER: ${{ secrets.SSH_USER }}
      # SSH_HOST: ${{ secrets.SSH_HOST }}
      # SSH_PASS: ${{ secrets.SSH_PASS }}
      SSH_USER: ${{ secrets.SFTP_USER }}
      SSH_HOST: ${{ secrets.SFTP_HOST }}
      SSH_PASS: ${{ secrets.SFTP_PASS }}
      JAR_FILENAME: prueba.jar

    steps:
      - name: check variables
        if: ${{env.SSH_PASS}} != '' && ${{env.SSH_USER}} != '' && ${{env.SSH_HOST}} != ''
        run: |
          echo "Variables de entorno no vacias"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with: 
          java-version: '8'
          distribution: 'temurin'

      - name: Build and package
        run: |
          mvn clean package

      - name: Rename JAR file
        run: |
          mv target/WarningPoints-1.0.jar target/${{env.JAR_FILENAME}}

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh

      - name: Add host key to known hosts
        run: |
          ssh-keyscan -t rsa ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install expect
        run: |
          sudo apt-get update && sudo apt-get install -y expect

      - name: Deploy to SFTP
        run: |
          expect -c "
          spawn sftp -P 2022 ${{ env.SSH_USER }}@${{ env.SSH_HOST }}
          expect \"password:\"
          send \"${{ env.SSH_PASS }}\r\"
          expect \"sftp>\"
          send \"put target/${{env.JAR_FILENAME}} plugins\r\"
          expect \"sftp>\"
          send \"bye\r\"
          "


      # - name: SFTP uploader
      #   uses: wangyucode/sftp-upload-action@v2.0.2
      #   with:
      #     host: ${{ env.SSH_HOST }}
      #     password: ${{ env.SSH_PASS }}
      #     username: ${{ env.SSH_USER }}
      #     localDir: 'target/WarningPoints-1.0.jar'
      #     remoteDir: '/plugins/WarningPoints-TEST.jar'

      # - name: Connect
      #   id: connect
      #   uses: danhendrickson/sftp-transfer-action@v1.23
      #   with:
      #     server: ${{ env.SSH_HOST }}
      #     user: ${{ env.SSH_USER }}
      #     pass: ${{ env.SSH_PASS }}
      #     port: 2022
      #     local-path: 'target/WarningPoints-1.0.jar'
      #     remote-path: '/plugins/WarningPoints-TEST.jar'

      # - name: Transfer Status
      #   run: echo "Transfer Status - ${{ steps.connect.outputs.transferStatus }}"